# Ubuntu
ubuntu-install:
	./ubuntu/install.sh

# Centos. Not tested yet, but should work.
centos-install:
	./centos/install.sh

clean:
	sudo rm -rf /etc/nginx
	sudo rm -f /sbin/nginx
	sudo rm -rf /var/log/nginx
	sudo rm -f /run/nginx.pid